### ISSUE TITLE
Launcher self-update doesn't work if the launcher executable has been renamed

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTC-Launcher#15]
1. Download the RTC launcher off of the website
2. Rename the exe
3. Get prompted to update the launcher
4. File not found error

**Comment by NarryG** [comment]
That's an annoying regression. This was an issue in the past that we had resolved.

**Comment by NarryG** [comment]
Resolved with https://github.com/redscientistlabs/RTC-Launcher/commit/b9c1f0a75b64fd756d25f405da91524e46edb029
