### ISSUE TITLE
[Dev] Can't open Form classes in Form Designer in Visual Studio

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTC-Launcher#16]
![image](https://user-images.githubusercontent.com/1100550/93833701-3d939a00-fc2e-11ea-9bc0-e00de80b818f.png)

**Comment by NarryG** [comment]
Going to revert the project type update PR as they're showing as forms for me but then VS crashes when it tries to draw them. I could have sworn it was working before I merged it.

**Comment by NarryG** [comment]
Fixed with b699e01cf3bd51ea8f5bb772e901512f63632f65
If you want to open that back up as a PR, we can attempt to figure out why VS is being  weird

**Comment by scowalt** [comment]
FYI I figured out what is going on here. I'll re-submit a PR for the new project format
